config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/saps-dashboard:
      branch: master
      repo: https://github.com/EOSC-synergy/saps-dashboard
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/saps-dashboard git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-denim-squid.sh
        container: qc.acc_muggy-gamboge-mammoth
  QC.Doc:
    repos:
      github.com/EOSC-synergy/saps-dashboard find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-cobalt-mau.sh
        container: qc.doc_craggy-charcoal-wrasse
      github.com/EOSC-synergy/saps-dashboard git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-charcoal-iguana.sh
        container: qc.doc_snazzy-myrtle-tzu
      github.com/EOSC-synergy/saps-dashboard markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-viridian-flounder.sh
        container: qc.doc_zippy-tan-serval
  QC.Lic:
    repos:
      github.com/EOSC-synergy/saps-dashboard licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-saffron-fossa.sh
        container: qc.lic_skimpy-yellow-cat
  QC.Sec:
    repos:
      github.com/EOSC-synergy/saps-dashboard bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-grey-monster.sh
        container: qc.sec_beady-cinnabar-ragdoll
  QC.Sty:
    repos:
      github.com/EOSC-synergy/saps-dashboard flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-myrtle-scorpion.sh
        container: qc.sty_beady-sangria-shark
  QC.Ver:
    repos:
      github.com/EOSC-synergy/saps-dashboard get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-eggplant-bison.sh
        container: qc.ver_thirsty-fuchsia-mayfly
timeout: 1800
